### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by eric-f** [UBC-MDS/DSCI_522_Salary-vs-College#34]
__Mechanics__
- [x] Could have edited the README from the proposal version more. E.g. at the very beginning, tell a nice little story about this project. Make it intriguing and inviting to read one.
- [x] Right now each section answers a question in the 'lab instruction'. Might want to combine them and provide a project overview that is more narrative than administrative?
- [x] Should have included a section in README explaining how to run your data analysis, e.g. script order, expected inputs, outputs.
- [x] Add a link to the report somewhere in README(?)

__Quality__
- [x] Documentation missing for some scripts. Need a blurb at the top stating the author(s), date created and a brief description.
- [x] In addition to showing an usage example, could have explain what the arguments mean. (input file? output folder?)

__Report__
- [x] Would be nice to give every figure a title. Even better if you add a caption for each figure.
Also, can we center-justify the figure labels?
- [x] Maybe we can silence the R messages in the results section?
- [x] Tables 1 and 3 are too long. How about show a shortened version with a more focused message? Keep the full table in a separate md file and provide a link in the full report instead. Maybe there are other ways to hide these intimidating tables.
- [x] Reference section is empty

**Comment by lyyu0413** [comment]
Quality
1. Re-edit all the scripts, now every script has an appropriate documentation
2. Re-edit all the usage massage, now every script has the expiration for all the arguments

Report
2. Use suppressPackageStartupMessages() function to silence all the R warning massages when importing the library.

**Comment by lyyu0413** [comment]
Report
1. Added title to ever figures with the figure number. The title are all centred;
3. Add reference section.

**Comment by pak-alex** [comment]
Mechanics: 

README was updated to include motivation, project reproduction, link to report in the README. See 403bccf9f8c73e31fd1612b4a0df220d04341702 for more details.

Report: 

Tables were shortened to only include the relevant points in the final report. Full ANOVA/Tukey comparisons can be seen in the results section.
